apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-vote-frontend-configmap
  namespace: dev
  annotations:
    description: "frontend configmap"
data:
  # property-like keys; each key maps to a simple value
  REDIS: "azure-vote-back"